### ISSUE TITLE
GPS Module Interface

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#8]
How to get the coordinates (longitude and latitude) and switch to the related map using a mobile application?

**Comment by punisha1996** [comment]
In my task according to task list, I have to interface GPS with Rpi4 
but as you raised a issue about how we will be able to display the
exact location on Care Taker's Mobile. So in final project,
suppose if there will be any uncertainty occur like, Oldster fall or Pulse
rate increased then, using GSM will send an SMS to care Taker's mobile
which does contains whole data like, 

(Message Format)
XYZ Name
Pulse : 45 BPM
Location: https://www.google.co.in/maps/place/<latitude,longitude>


So let us assume that we get 50.23379, -86.98350 as latitude and longitude
so instead of <latitude,longitude> just type 50.23379, -86.98350 along with
rest of link like below

https://www.google.co.in/maps/place/50.23379,-86.98350

So when Care taker open SMS sent by GSM, then they will find
a link like above one and if they clicked on link then
they will get pop up message about to open link in browser
so with without copy and paste they will easily get the current
location of oldster with just one click on SMS link.

This is how family member one who's number registered in program can
get information about the oldster.
